### ISSUE TITLE
Invalid Sample Video Thumbnail URLs

### ISSUE THREAD

**Issue by navaneethred** [adrianhajdin/aora#1]
The URLs for the dummy video's thumbnails are invalid.

**Comment by svashish305** [comment]
I faced the same issue,
for eg for thumbnail URL for title "Get inspired to code"
https://cloud.appwrite.io/v1/storage/buckets/660d0e59e293896f1eaf/files/660eff632e9b0[%E2%80%A6]ht=2000&gravity=top&quality=100&project=660d0e00da0472f3ad52
on opening in new tab I get error:
{
  "message": "Invalid `fileId` param: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore",
  "code": 400,
  "type": "general_argument_invalid",
  "version": "0.12.148"
}

**Comment by sujatagunale** [comment]
@navaneethred and @svashish305, thank you for reporting the issue. It has now been fixed!
