### ISSUE TITLE
Getting Error in Create Post  

### ISSUE THREAD

**Issue by HerbertNtim** [adrianhajdin/aora#10]
![WhatsApp Image 2024-04-23 at 03 33 26_bdca6c27](https://github.com/adrianhajdin/aora/assets/104742927/39ebcd29-34e6-45f6-ad85-fe5c9454b0ec)
1. I got this error "Error: TypeError: Cannot read property '$id' of undefined " and now i implemented if else condition to check the uploaded file if it exists or not..... after that i got the else statement that the file upload failed.

2. Currently there another issue with appwrite which is "video and thumbnail are required"  even though i have uploaded them from my local phone storage, I can't still make the file submission to the database

3. I am also getting cannot read property 'username' of null in the home.jsx page

**Comment by OtaraAlex** [comment]
![create jsx - Aora - Visual Studio Code 4_22_2024 10_09_42 PM](https://github.com/adrianhajdin/aora/assets/111053808/937e1e62-c8a3-451e-998a-4ecce9c6075d)

Getting a similar error, initialy the DocumentPicker worked and the video got published but using the ImagePicker the assetId is null hence it can not be submitted.

**Comment by HerbertNtim** [comment]
Okay thank you but how did you solve it?
