### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'useMemo' of null

### ISSUE THREAD

**Issue by uthamprabhu** [adrianhajdin/aora#13]
The below error message is coming after the prerequisite completion and running the app on mobile. 
 
 ERROR  TypeError: Cannot read property 'useMemo' of null

This error is located at:
    in ContextNavigator (at ExpoRoot.js:64)
    in ExpoRoot (at qualified-entry.js:20)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (at withDevTools.js:18)
    in withDevTools(ErrorOverlay) (at renderApplication.js:57)        
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComponent) (at renderApplication.js:67), js engine: hermes

This error is located at:
    in ContextNavigator (at ExpoRoot.js:64)
    in ExpoRoot (at qualified-entry.js:20)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (at withDevTools.js:18)
    in withDevTools(ErrorOverlay) (at renderApplication.js:57)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComponent) (at renderApplication.js:67), js engine: hermes

**Comment by cesarrsegovia** [comment]
i have the same error. any solution?

**Comment by 1KEBRON** [comment]
this solved it for me , used this version package.json and used yarn install instead of npm.

{
  "name": "aora",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~50.0.14",
    "expo-av": "~13.10.5",
    "expo-constants": "~15.4.6",
    "expo-device": "^5.9.3",
    "expo-document-picker": "~11.10.1",
    "expo-font": "~11.10.3",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.9",
    "expo-status-bar": "~1.11.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-animatable": "^1.4.0",
    "react-native-appwrite": "^0.2.2",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.24.3",
    "tailwindcss": "3.3.2"
  },
  "private": true
}

**Comment by merenlmtr** [comment]
- run `npx expo install react-dom` in your project, then run `npm why react-dom` to verify that you only have 18.2.0 installed
- use the `--legacy-peer-deps` option with npm
- use another package manager like yarn
this solved in my case.
