### ISSUE TITLE
in video card, dummy video link and thumb nail link have issue

### ISSUE THREAD

**Issue by feihuan1** [adrianhajdin/aora#16]
here is the response for the video link and thumbnail link, is there a way not upgrade and use it?
{"message":"Bandwidth limit for your organization has exceeded. Please upgrade to higher plan or update budget cap.","code":402,"type":"bandwidth_limit_exceeded","version":"0.13.6"}

**Comment by filipedsantos** [comment]
I had the same error when I was trying to load the thumbnails with the links coming from JSMastery. Try to upload a file to your appwrite account and use the link to your file. That worked for me.

**Comment by sujatagunale** [comment]
Assets links have been updated. You can choose to use other assets as well 👍
