### ISSUE TITLE
 Font not working properly on android

### ISSUE THREAD

**Issue by Yassin-Zaher** [adrianhajdin/aora#17]
the font is not loading properly, the next warning shows up when running the app and adding font-psemibold to  **<Text className="text-primary text-lg font-psemibold">CustomButton</Text>**
WARN **fontFamily** "Poppins-SemiBold" is not a system font and has not been loaded through expo-font.
note: i copied the code from the original repo and the font folder is in the correct place  ./assets/fonts/Poppins-Bold.ttf

**Comment by Yassin-Zaher** [comment]
Worked after putting the code that loads the fonts in the `app/index.jsx`

**Comment by KhalidAlghamdi8** [comment]
can u help? i was traying you method but still getting  is not a system font and has not been loaded through expo-font
