### ISSUE TITLE
AppwriteException: Network request failed

### ISSUE THREAD

**Issue by jelopez03** [adrianhajdin/aora#18]
I get AppwriteException: Network request failed, when I click signup at time: 1:44:19.

Can someone help?

**Comment by jelopez03** [comment]
Wrong endpoint URL.

**Comment by ankitjasbeersingh** [comment]
how it is resolved what your endpoint I'm still getting this error my endpoint is this one sometimes it works but most of the time it doesn't

**Comment by ankitjasbeersingh** [comment]
I'm using this endpoint https://cloud.appwrite.io/v1
