### ISSUE TITLE
Sample Videos not playing

### ISSUE THREAD

**Issue by svashish305** [adrianhajdin/aora#2]
The video urls given for sample videos aren't playing in finished app or new tab, on opening this link in new tab for eg:
URL: https://cloud.appwrite.io/v1/storage/buckets/660d0e59e293896f1eaf/files/660f004955f51e7e3212/view?project=660d0e00da0472f3ad52
Response:
{
  "message": "Bandwidth limit for your organization has exceeded. Please upgrade to higher plan or update budget cap.",
  "code": 402,
  "type": "bandwidth_limit_exceeded",
  "version": "0.12.148"
}

**Comment by thesmol** [comment]
Play works with your videos uploaded to Appwrite

**Comment by alsyferr** [comment]
Play works with your own videos. watch the tutorial to the end and learn how to upload from your phone.

**Comment by svashish305** [comment]
I confirm it works with own uploaded videos, guess we can replace the sample video files as a fix, we can close this issue.
