### ISSUE TITLE
Can't setup Nativewind for the app!

### ISSUE THREAD

**Issue by aditya-2k23** [adrianhajdin/aora#26]
I have installed all the necessary dependencies for nativewindcss with tailwindcss version ^3.3.2.
I don't know why nativewind is not working on the app.
I also recreated the whole app and after installing the nativewind and doing changes in tailwind.config.js I have also restarted the development server of the app.
But still no luck. 🥲

**Comment by aditya-2k23** [comment]
Ok, so after rebundling the entire server using `npx expo start -c` command. It worked 🥳

**Comment by alieldeba** [comment]
Note: Nativewind does not work on web it works only with android and iPhone if someone wants it to run on the web he should make more configurations that they are provided in their docs
