### ISSUE TITLE
 ' WARN  Layout children must be of type Screen, all other children are ignored. To use custom children, create a custom <Layout />. Update Layout Route at: "app/(tabs)/_layout"'

### ISSUE THREAD

**Issue by Pannu786** [adrianhajdin/aora#29]
if someone else facing the same warning issue you need to remove these "{' '}". Your welcome.

**Comment by mrbgit** [comment]
I am facing this same issue in AuthLayout/SignIn. I didn't get which "{''}" do you refer? @Pannu786
