### ISSUE TITLE
putting real username in home.jsx

### ISSUE THREAD

**Issue by PARVNEMA** [adrianhajdin/aora#3]
you have written jsmMastry in username in home instead you can can import Globalcontext user and put user.username in place of JSMastery

**Comment by bonacciniWd** [comment]
could you add that code on your home screen code for it:

**First**- 🥇  import the GlobalContext :

`import { useGlobalContext } from "../../context/GlobalProvider";`

then, add a new const -

`const { user } = useGlobalContext(); `

and finally, change the Text render component

 ```
              <Text className="text-2xl font-psemibold text-white">
                  {user?.username}     
              </Text>
```

**Comment by HerbertNtim** [comment]
Alright thank you for the help
