### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'username' of null after registration new user and login

### ISSUE THREAD

**Issue by LesyaTT** [adrianhajdin/aora#30]
ERROR  TypeError: Cannot read property 'username' of null on all pages where it uses after register new user and login
 
<img width="357" alt="Screenshot 2024-06-09 at 11 08 26 PM" src="https://github.com/adrianhajdin/aora/assets/104120539/7cd8c673-2e0e-42ea-b634-102dd65a03f0">

**Comment by FriendlyMaabuat** [comment]
How did you fix it? I think I'm facing a similar issue
![image](https://github.com/adrianhajdin/aora/assets/92776515/2dde417d-634c-4322-a1bd-09971b5f950a)
