### ISSUE TITLE
Issues with Videos Collection Update and Index Creation

### ISSUE THREAD

**Issue by Rajkumar-Khatua** [adrianhajdin/aora#7]
Hello Guys, I would like to bring to your attention some challenges I've encountered while building the project by following the tutorial:

**1. Videos Collection Update Issue:**
Upon review, I've noticed that the videos collection is not updating as expected. Despite attempts to make modifications, the changes are not reflecting in the collection.

**2. Videos Collection Attribute Update Problem:**
Additionally, I've encountered difficulties updating attributes within the videos collection. Despite efforts to modify attributes, they remain unchanged, impacting the integrity of our data.

**3. Videos Collection Index Creation Failure:**
Furthermore, I've observed that the indexes for the videos collection are not being created. This is hindering our ability to efficiently access and manage the data within the collection.

![Issue](https://github.com/adrianhajdin/aora/assets/124782492/8edc0cee-a69f-475b-b52d-4c32ddb17e2f)

I kindly request your assistance in addressing these issues promptly. If further information or clarification is needed, please do not hesitate to reach out.

Thank you for your attention to this matter.

**Comment by sujatagunale** [comment]
@Rajkumar-Khatua, try to create a whole new project on Appwrite. If the issue persists, you can reach out to [Appwrite on Discord](https://discord.gg/dUTmNj2S) or [raise a Github issue](https://github.com/appwrite/console/issues) there
